---
title: "Biography"
---

### Education

* PhD in Statistics, University of Copenhagen, Denmark, Sep. 2021 -- Feb. 2025 
* MMath in Statistics, University of Waterloo, Canada, Sep. 2017 -- Dec. 2018
* BMath in Computational Mathematics joint Statistics, University of Waterloo, Canada, Sep. 2016 -- June 2017
* BA in Mathematical Economics, University of Waterloo, Canada, Sep. 2014 -- June 2016

### Work

* Postdoctoral fellow, ISTA, Klosterneuburg, Austria, Feb. 2025 -- present
* Guest Researcher, Novo Nordisk, Copenhagen, Denmark, Apr. 2024 -- Aug. 2024
* Data Scientist (intern), Google France, Paris, France, Sep. 2023 -- Nov. 2023
* Statistical Programmer & Data Scientist, Hoffmann-La Roche, Mississauga, ON, Canada, Jan. 2019 -- Jun. 2021

### Languages

* English
* Mandarin Chinese

### Personal background

I was born and raised in [Tianjin](https://goo.gl/maps/Z9mNuf78ABCCQwfu6), China, and my name in Chinese characters is 黄诗萌. In September 2012, I moved to Beijing to start my undergraduate study at [Beijing Jiaotong University](http://en.njtu.edu.cn/). In July 2014, I continued my study at the [University of Waterloo](https://uwaterloo.ca/), Ontario, Canada. After spending some enjoyable years there and in the Greater Toronto Area (Mississauga and Toronto, specifically) for study and work, I decided to move to Copenhagen, Denmark, to pursue my PhD degree in September 2021. I now live in Vienna, Austria. 
